version: '3'
services:
  web:
    build: .
    depends_on:
      - "dynamodb-container"
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3010:3000"
  dynamodb-container:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    volumes:
      - dynamodb_data:/home/dynamodblocal
    ports:
      - "8000:8000"

volumes:
  dynamodb_data:
