version: '3'
services:
  web-dev:
    build: .
    depends_on:
      - "dynamodb-dev-container"
    command: npm run dev-env
    volumes:
      - .:/app/
      - /usr/app/node_modules
    ports:
      - "3010:3010"
  dynamodb-dev-container:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    volumes:
      - dynamodb_data:/home/dynamodblocal
    ports:
      - "8000:8000"

volumes:
  dynamodb_data:
